   export interface InstituteList{
      "institute_Category": string,
      "institute_Name": string,
      "institute_State": string,
      "institute_District": string,
      "institute_Code": Number,
      "dise_Code": string,
      "location": string,
      "institute_Type": string,
      "affiliated_Uni_State": string,
      "affiliated_Uni_Name": string,
      "year_Admission_Start": string,
      "institute_Est_Certificate": string,
      "university_Certificate": string,
      "address_1": string,
      "address_2": string,
      "city": string,
      "address_State": string,
      "address_District": string,
      "address_Pincode": string,
      "principle_Name": string,
      "principle_MobileNo": string,
      "status": string
  }